/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9ef5f97b9b64261fbc05ee2cb5b0f7ea)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	RWSDK_JEOPARDY_ENV: "integration" | "staging" | "production" | "development";
	WEBAUTHN_APP_NAME: "kad-jeopardy";
	SESSION_SECRET_KEY: string;
	D1_JEOPARDY: D1Database;
	AED_LOGIN_ATTEMPTS: AnalyticsEngineDataset;
	AI: Ai;
	LOG_LEVEL: "debug";
	LOG_LEVEL_TASK_OVERRIDE: "";
	SESSION_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
	SYNCED_STATE_SERVER: DurableObjectNamespace<import("./src/worker").SyncedStateServer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SyncedStateServer";
	}
	interface IntegrationEnv {
		ASSETS: Fetcher;
		RWSDK_JEOPARDY_ENV: "integration";
		WEBAUTHN_APP_NAME: "kad-jeopardy";
		SESSION_SECRET_KEY: string;
	}
	interface StagingEnv {
		ASSETS: Fetcher;
		RWSDK_JEOPARDY_ENV: "staging";
		WEBAUTHN_APP_NAME: "kad-jeopardy";
		SESSION_SECRET_KEY: string;
	}
	interface ProductionEnv {
		ASSETS: Fetcher;
		RWSDK_JEOPARDY_ENV: "production";
		WEBAUTHN_APP_NAME: "kad-jeopardy";
		SESSION_SECRET_KEY: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RWSDK_JEOPARDY_ENV" | "WEBAUTHN_APP_NAME" | "SESSION_SECRET_KEY" | "LOG_LEVEL" | "LOG_LEVEL_TASK_OVERRIDE">> {}
}
