/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 3cd36941651a34909a22e29198d55166)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SyncedStateServer";
	}
	interface Env {
		ASSETS: Fetcher;
		VITE_BASE_URL: string;
		RWSDK_JEOPARDY_ENV: string;
		SESSION_SECRET_KEY: string;
		SYNCED_STATE_SERVER: DurableObjectNamespace<import("./src/worker").SyncedStateServer>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VITE_BASE_URL" | "RWSDK_JEOPARDY_ENV" | "SESSION_SECRET_KEY">> {}
}
