/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: c67c75153ff03055932f19dfa595a808)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SyncedStateServer";
	}
	interface IntegrationEnv {
		RWSDK_JEOPARDY_ENV: "integration";
		VITE_BASE_URL: string;
		VITE_APP_VERSION: string;
	}
	interface StagingEnv {
		RWSDK_JEOPARDY_ENV: "staging";
		VITE_BASE_URL: string;
		VITE_APP_VERSION: string;
	}
	interface ProductionEnv {
		RWSDK_JEOPARDY_ENV: "production";
		VITE_BASE_URL: string;
		VITE_APP_VERSION: string;
	}
	interface Env {
		VITE_BASE_URL: string;
		VITE_APP_VERSION: string;
		RWSDK_JEOPARDY_ENV: "integration" | "staging" | "production" | "development";
		AI: Ai;
		ASSETS: Fetcher;
		SYNCED_STATE_SERVER: DurableObjectNamespace<import("./src/worker").SyncedStateServer>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RWSDK_JEOPARDY_ENV" | "VITE_BASE_URL" | "VITE_APP_VERSION">> {}
}
