import { describe, expect, it } from 'vitest';
import { streamlineError, validateUuid } from '../utils';

describe('validateUuid', () => {
	it('returns true for a valid UUID', () => {
		expect(validateUuid('550e8400-e29b-41d4-a716-446655440000')).toBe(true);
	});

	it('returns true for a UUID generated by crypto.randomUUID', () => {
		expect(validateUuid(crypto.randomUUID())).toBe(true);
	});

	it('returns false for a non-UUID string', () => {
		expect(validateUuid('not-a-uuid')).toBe(false);
	});

	it('returns false for an empty string', () => {
		expect(validateUuid('')).toBe(false);
	});

	it('returns false for a UUID with wrong segment lengths', () => {
		expect(validateUuid('550e8400-e29b-41d4-a716-44665544000')).toBe(false);
	});
});

describe('streamlineError', () => {
	it('wraps a non-Error value in a new Error', () => {
		const result = streamlineError('some string error');
		expect(result.error).toBeInstanceOf(Error);
		expect((result.error as Error).message).toBe('some string error');
		expect(result.message).toBe('');
	});

	it('returns the Error directly when err is an Error without a cause', () => {
		const err = new Error('top level error');
		const result = streamlineError(err);
		expect(result.error).toBe(err);
		expect(result.message).toBe('');
	});

	it('includes cause message when err is an Error with an Error cause', () => {
		const cause = new Error('root cause message');
		const err = new Error('top level', { cause });
		const result = streamlineError(err);
		expect(result.error).toBe(err);
		expect(result.message).toBe(': root cause message');
	});

	it('ignores cause when err is an Error but cause is not an Error', () => {
		const err = new Error('top level');
		(err as any).cause = 'string cause';
		const result = streamlineError(err);
		expect(result.error).toBe(err);
		expect(result.message).toBe('');
	});
});
